services:
  app:
    image: filebrowser/filebrowser:v2.63.23
    restart: unless-stopped
    ports:
      - "127.0.0.1:${LION_APP_PORT}:80"
    volumes:
      - ${LION_MEDIEN}:/srv
      - ${LION_APP_DATA}/datenbank:/database
    security_opt:
      - no-new-privileges:true
